// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv';
import { defineConfig } from 'prisma/config';

dotenv.config({
  path: `.env.${process.env.NODE_ENV || 'development'}`,
});

console.log('NODE_ENV =', process.env.NODE_ENV);
console.log('DATABASE_URL exists =', !!process.env.DATABASE_URL);

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
